//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogOfFilms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decennary
    {
        public Decennary()
        {
            this.Films = new HashSet<Film>();
        }
    
        public int Id { get; set; }
        public int Years { get; set; }
    
        public virtual ICollection<Film> Films { get; set; }
    }
}
